### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'imgix_subdomains') 

### ISSUE THREAD

**Issue by defjosiah** [imgix/contentful#116] opened 2022-03-29 00:33 UTC
Please provide the following information and someone from @imgix/imgix-sdk-team will respond to your issue shortly.

**Describe the bug**

Set-up an initial integration with imgix and contentful, receive "TypeError: Cannot read properties of undefined (reading 'imgix_subdomains')" when attempting to "Add an Origin Image".

**To Reproduce**

- Add the imgix app to contentful
- Add a key to contenful
- Create a new "Content Type" called "imageAsset" with a single field "image" that is a "JSON field". Assign the imgix entry view to that field.
- Attempt to add using "Add an Origin Image"

**Expected behavior**

I expected that I would be able to add an image. (And that the "Select an imgix source") dropdown would be populated.

**Screenshots**

![Screen Shot 2022-03-28 at 5 31 07 PM](https://user-images.githubusercontent.com/3061661/160509226-b3649805-406c-4d9f-a3df-8413cf6676d8.png)

**Information:**
 - @imgix/contentful version: Not totally sure, I just installed the latest one from the contentful UI.

**Additional context**

I first expected that it was an issue with the API key. However, I verified in the dev console that the API request to `Request URL: https://api.imgix.com/api/v1/sources` is correctly going through and returns JSON data that looks correct.

**Comment by heyitsbryanm** [comment] 2022-03-29 18:50
Looked into it, and this is most likely caused by a Source configuration on the imgix end.

It looks like your Source didn't have Image Manager enabled. We just fixed it on the imgix side, you can check again in an hour or two to see if this fixes the problem.

**Comment by sherwinski** [comment] 2022-04-05 22:56
@defjosiah I'm going to close this issue now as it seems that the issue was resolved offline. Please feel free to reopen if that is not the case.

**Closed by sherwinski** 2022-04-05 22:56 UTC
Labels: bug
